[workspace]
members = [
    "icarus",
    "icarus-app",
    "icarus-cli",
    "icarus-test",
    "icarus-comms",

    "serial-ppp",

    # External packages for patching crates.io
    "external/mpu6050"
]

[patch.crates-io]
mpu6050 = {path = "external/mpu6050"}
