[package]
name = "icarus-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icarus-comms = {path = "../icarus-comms"}
clap = {version = "3.0.0-rc.4", features = ["derive"]}
serialport = "4.0"
