[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "cargo flash --release --chip STM32F405RGTx --connect-under-reset"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
