cargo-features = ["per-package-target"]

[package]
name = "icarus-app"
version = "0.1.0"
edition = "2018"
forced-target = "riscv32imc-unknown-none-elf"

[dependencies]
riscv-rt = "0.8"
icarus = {path = "../icarus"}
panic-halt = "0.2"
defmt = "0.3"
# defmt-bbq = "0.1"
heapless = "0.7.8"
