cargo-features = ["per-package-target"]

[package]
name = "icarus-app"
version = "0.1.0"
edition = "2018"
forced-target = "thumbv7em-none-eabihf"

[dependencies]
icarus = {path = "../icarus"}
panic-halt = "0.2"
cortex-m-rtic = "0.6.0-rc.4"
