[package]
name = "icarus-comms"
version = "0.1.0"
edition = "2021"
description = "Common icarus communication data structures"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial-ppp = {path = "../serial-ppp"}
