cargo-features = ["per-package-target"]

[package]
name = "icarus-test"
version = "0.1.0"
edition = "2018"
forced-target = "thumbv7em-none-eabihf"

[dependencies]
icarus = {path = "../icarus"}
panic-halt = "0.2"
